"""Harness integration: pushing enforcement earlier than the diff.

`capsule verify` checks a change after it exists. That is a real gate, but it is
the last one available — the edit already landed, and the agent already spent the
turn. The host harness exposes two earlier points, and a contract can be
translated into both:

  1. **Permission rules.** A command-shaped prohibition (`npm install`, `cat`)
     becomes a `deny` rule the harness evaluates *before running the command*.
     Nothing executes, so there is nothing to undo.

  2. **PreToolUse hooks.** A code-shaped prohibition (`SOLID`, `yaml.load`, `•`)
     cannot be a permission rule — the harness matches command patterns, not file
     contents. But a `PreToolUse` hook on `Write|Edit` sees the pending content
     and can block the call, so the banned token never reaches disk.

That split is not arbitrary; it falls out of the corpus. Of the prohibitions
extracted from the mounted skills, five are command-shaped and thirty-one are
code-shaped, so both paths are needed to cover the set.

Ordering, weakest to strongest:

    skill body says it     ->  a hint the model may act on
    capsule verify         ->  fails the commit after the fact
    PreToolUse hook        ->  blocks the write before it lands
    permission deny rule   ->  the command never runs

**A caveat that matters.** Hook input field names are harness-specific and change
between versions. The generated script probes several plausible names and fails
*open* with a clear message when it recognises nothing, rather than silently
passing everything or blocking everything. Verify the field names against your
harness version before relying on it; the script prints what it saw with
`CAPSULE_HOOK_DEBUG=1`.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass, field
from pathlib import Path

from .contract import FORBID, PLACEMENT, Contract, Obligation

# Binaries a prohibition can name. A token starting with one of these is a
# command, so it belongs in a permission rule rather than a content check.
_COMMAND_HEADS = (
    "npm", "npx", "pnpm", "yarn", "pip", "pip3", "python", "python3", "node",
    "cat", "head", "tail", "rm", "mv", "cp", "git", "curl", "wget", "brew",
    "apt", "apt-get", "sudo", "chmod", "chown", "docker", "kubectl", "make",
)

_COMMAND_RE = re.compile(rf"^({'|'.join(map(re.escape, _COMMAND_HEADS))})\b")


@dataclass
class Emission:
    """One generated harness artifact."""

    path: str
    content: str
    note: str = ""


def is_command_token(token: str) -> bool:
    return bool(_COMMAND_RE.match(token.strip()))


def split_obligations(contract: Contract) -> tuple[list[Obligation], list[Obligation]]:
    """Partition prohibitions into (command-shaped, content-shaped)."""
    commands, contents = [], []
    for obligation in contract.checkable:
        if obligation.kind != FORBID:
            continue
        (commands if is_command_token(obligation.token) else contents).append(obligation)
    return commands, contents


# -- permission rules ----------------------------------------------------------


def permission_rules(contract: Contract) -> dict:
    """Translate command-shaped prohibitions into harness deny rules.

    Rule format is `ToolName(specifier)`; Bash specifiers are command patterns,
    so `npm install` becomes `Bash(npm install *)`. Only `deny` is emitted:
    Capsule's own policy escalates and never loosens, and generating `allow`
    rules from a skill body would widen a user's permissions on the strength of
    a regex match, which is the wrong direction to be wrong in.
    """
    commands, _ = split_obligations(contract)
    deny = []
    for obligation in commands:
        token = obligation.token.strip()
        pattern = f"Bash({token} *)" if " " in token else f"Bash({token} *)"
        if pattern not in deny:
            deny.append(pattern)
    return {
        "permissions": {"deny": deny},
        "_capsule": {
            "skill": contract.skill,
            "generated_from": "contract prohibitions with command-shaped tokens",
            "coverage_note": (
                f"{len(deny)} of {len(contract.checkable)} enforceable obligations are "
                "command-shaped and preventable here; the rest need the PreToolUse hook"
            ),
        },
    }


# -- PreToolUse hook -----------------------------------------------------------

_HOOK_SCRIPT = '''#!/usr/bin/env python3
"""Capsule PreToolUse hook: block writes that violate the active skill contract.

Generated by `capsule harness`. Reads the hook event on stdin, extracts the
pending file content, and checks it against the contract's content-shaped
prohibitions. Exits non-zero to block the tool call.

Field names in the hook payload are harness- and version-specific. This script
probes several plausible names and, when it recognises none, fails OPEN with a
message on stderr rather than blocking every edit. Set CAPSULE_HOOK_DEBUG=1 to
print the payload keys it actually received.
"""

import json
import os
import sys

# Injected by `capsule harness`: token -> the directive that prohibits it.
PROHIBITED = __PROHIBITED__
SKILL = __SKILL__

# Keys that have carried pending file content across harness versions.
CONTENT_KEYS = ("content", "new_string", "new_str", "text", "replacement")
PATH_KEYS = ("file_path", "path", "filePath", "notebook_path")


def _first(payload, keys):
    for key in keys:
        value = payload.get(key)
        if isinstance(value, str) and value:
            return key, value
    return None, None


def main() -> int:
    try:
        event = json.load(sys.stdin)
    except (json.JSONDecodeError, ValueError):
        print("capsule-hook: unparsable event payload; allowing", file=sys.stderr)
        return 0

    tool_input = event.get("tool_input") or event.get("toolInput") or {}
    if not isinstance(tool_input, dict):
        tool_input = {}

    if os.environ.get("CAPSULE_HOOK_DEBUG"):
        print(f"capsule-hook: event keys={sorted(event)} "
              f"tool_input keys={sorted(tool_input)}", file=sys.stderr)

    content_key, content = _first(tool_input, CONTENT_KEYS)
    _, path = _first(tool_input, PATH_KEYS)

    if content is None:
        # Nothing recognisable to inspect. Failing open is deliberate: a hook that
        # blocks whatever it cannot parse makes the harness unusable after any
        # payload change, and people respond by removing the hook entirely.
        print(
            "capsule-hook: no content field recognised in tool_input "
            f"(looked for {', '.join(CONTENT_KEYS)}); allowing. "
            "Run with CAPSULE_HOOK_DEBUG=1 and update CONTENT_KEYS.",
            file=sys.stderr,
        )
        return 0

    violations = [
        (token, directive)
        for token, directive in PROHIBITED.items()
        if token in content
    ]
    if not violations:
        return 0

    where = f" in {path}" if path else ""
    print(f"Blocked by the {SKILL} skill contract{where}:", file=sys.stderr)
    for token, directive in violations[:5]:
        print(f"  - introduces {token!r}: {directive}", file=sys.stderr)
    print(
        "\\nThis is a rule from the skill pack governing this task, not a "
        "permission problem. Revise the content or ask the user to override.",
        file=sys.stderr,
    )
    return 2


if __name__ == "__main__":
    sys.exit(main())
'''


def hook_script(contract: Contract) -> str:
    """Render the PreToolUse checker with this contract's prohibitions baked in."""
    _, contents = split_obligations(contract)
    prohibited = {o.token: o.directive[:140] for o in contents}
    return (
        _HOOK_SCRIPT
        .replace("__PROHIBITED__", json.dumps(prohibited, indent=4, ensure_ascii=False))
        .replace("__SKILL__", json.dumps(contract.skill))
    )


def hook_config(contract: Contract, script_path: str = "${CLAUDE_PROJECT_DIR}/.claude/capsule-hook.py") -> dict:
    """Wire the checker into PreToolUse for file-writing tools."""
    return {
        "hooks": {
            "PreToolUse": [
                {
                    "matcher": "Write|Edit|NotebookEdit",
                    "hooks": [
                        {
                            "type": "command",
                            "command": f'python3 "{script_path}"',
                        }
                    ],
                }
            ]
        },
        "_capsule": {
            "skill": contract.skill,
            "note": (
                "Blocks a pending write when it introduces a token the skill prohibits. "
                "Matcher covers file-writing tools only; command prohibitions are "
                "handled by the generated permission rules instead."
            ),
        },
    }


# -- plugin manifest -----------------------------------------------------------


def plugin_manifest(contract: Contract, version: str = "0.1.0", description: str = "") -> dict:
    """A manifest that makes a reconstructed pack installable as a plugin.

    A pack with `SKILL.md` at its root and no `skills/` subdirectory loads as a
    single-skill plugin, and the frontmatter `name` sets the invocation name. So
    the manifest carries metadata and the generated hook, not a `skills` field.
    """
    manifest = {
        "$schema": "https://json.schemastore.org/claude-code-plugin-manifest.json",
        "name": contract.skill,
        "version": version,
        "description": description or f"Capsule-reconstructed pack: {contract.skill}",
        "hooks": "./hooks/hooks.json",
    }
    return manifest


# -- untrusted input tiers -----------------------------------------------------

# Retrieval modes, ordered by exposure. The middle tier is the one worth naming:
# a maintained index lowers prompt-injection risk without removing it, so
# "indexed" is neither safe nor equivalent to live fetching.
FETCH_DISABLED = "disabled"
FETCH_INDEXED = "indexed"
FETCH_LIVE = "live"

_FETCH_TIER_RANK = {FETCH_DISABLED: 0, FETCH_INDEXED: 1, FETCH_LIVE: 2}

_LIVE_FETCH = re.compile(
    r"(web_?fetch|web_?search|requests\.get|urlopen|httpx\.|fetch\(|curl |wget |scrape)",
    re.IGNORECASE,
)
_INDEXED_HINT = re.compile(r"(cached|index(ed)?\s+search|offline\s+fallback)", re.IGNORECASE)


@dataclass
class InputProvenance:
    """How much untrusted content a skill pulls in, and by what route."""

    skill: str
    tier: str
    evidence: list[str] = field(default_factory=list)

    @property
    def rank(self) -> int:
        return _FETCH_TIER_RANK[self.tier]

    def line(self) -> str:
        detail = f" ({'; '.join(self.evidence[:2])})" if self.evidence else ""
        return f"{self.skill}: untrusted-input tier = {self.tier}{detail}"


def classify_input_provenance(skill: str, body: str) -> InputProvenance:
    """Tier a skill by how it acquires external content.

    Treat every retrieved result as untrusted input. The tier records the route,
    because the route bounds the exposure: no fetching at all cannot be injected
    through, a maintained index narrows what an attacker can place in the path,
    and live fetching of arbitrary pages is fully open.

    This is deliberately about *ingestion*, not intent. A skill whose whole
    purpose is fetching web content is legitimate and still lands in the top
    tier — that is the point. Legitimacy is not the same as low exposure.
    """
    evidence = []
    live = _LIVE_FETCH.search(body)
    if not live:
        return InputProvenance(skill, FETCH_DISABLED)

    evidence.append(f"fetches: {live.group(0)!r}")
    if _INDEXED_HINT.search(body):
        evidence.append("mentions a cached or indexed path")
        return InputProvenance(skill, FETCH_INDEXED, evidence)
    return InputProvenance(skill, FETCH_LIVE, evidence)


# -- emission ------------------------------------------------------------------


def emit_all(contract: Contract, dest: str | Path) -> list[Emission]:
    """Generate every harness artifact for one contract."""
    commands, contents = split_obligations(contract)
    emissions = [
        Emission(
            "settings.json",
            json.dumps(permission_rules(contract), indent=2) + "\n",
            f"{len(commands)} command prohibition(s) -> deny rules (never run)",
        ),
        Emission(
            "hooks/hooks.json",
            json.dumps(hook_config(contract), indent=2) + "\n",
            "wires the checker into PreToolUse for Write|Edit",
        ),
        Emission(
            "capsule-hook.py",
            hook_script(contract),
            f"{len(contents)} content prohibition(s) -> blocked before the write lands",
        ),
        Emission(
            ".claude-plugin/plugin.json",
            json.dumps(plugin_manifest(contract), indent=2) + "\n",
            "makes the pack installable as a single-skill plugin",
        ),
    ]
    return emissions
